### PR TITLE
fix(versions): fix use relative path for versioned guides selection

### LINKED ISSUE #107: [Bug] Switching to old doc versions causes 404
Switching from `2.2.0-latest` to `2.1.0`:

Screenshot from 2023-04-27 22-33-08

The URL seems kinda messed up. This only happens in `Get Started` page.

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #107

### CODE REVIEW

**Review by tthvo — COMMENTED** [review]
~Still need to fix Get Started?~

~Screenshot from 2023-04-28 14-58-34~

**EDITED:** Oh wait! If I am on incognito, this does not happen but selecting the version directs me to the Guides. 

I think my browser cache the asset. But is this intentional to be redirected or Get Started should have versions too?

File: assets/javascript/guides-version-dropdown.js [hunk 1]
```diff
@@ -1,11 +1,11 @@
...
     $('#guidesindex-version-dropdown').on('change', function() {
-      var guideUrl = window.location.href.substring(window.location.href.indexOf("/guides/"));
-  
+      var url;
       if (this.value == 'latest') {
-        window.location.href = '/guides/';
+        url = '/guides/';
       } else {
-        window.location.href = '/version/' + this.value + guideUrl;
+        url = '/version/' + this.value + '/guides/';
```
Comment (tthvo) [inline assets/javascript/guides-version-dropdown.js:7]: To explain above comment: This seems to be used in both getting started and guides.

Comment (andrewazores) [reply assets/javascript/guides-version-dropdown.js:7]: I removed the version selector from Getting Started in the `version-230` branch, because I don't think we really want to bother explaining how to install prior unsupported versions.

Comment (tthvo) [reply assets/javascript/guides-version-dropdown.js:7]: Okayy sounds good!

**Review by tthvo — APPROVED** [review]
